language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  # Tagging
  - docker tag reverseproxy hungnguyen101196/reverseproxy:v3
  - docker tag udagram-api-feed hungnguyen101196/udagram-api-feed:v3
  - docker tag udagram-api-user hungnguyen101196/udagram-api-user:v3
  - docker tag udagram-frontend hungnguyen101196/udagram-frontend:v3

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hungnguyen101196/reverseproxy:v3
  - docker push hungnguyen101196/udagram-api-feed:v3
  - docker push hungnguyen101196/udagram-api-user:v3
  - docker push hungnguyen101196/udagram-frontend:v3